### PR TITLE
Add support for the Aqara vibration sensor (Model DJT11LM)

### PR DESCRIPTION
**Pull request by paolotremadio**
See https://github.com/ebaauw/homebridge-hue/issues/377

### CODE REVIEW

**Comment by ebaauw** [comment]
Thanks!

Look good functionally, but better add
```javascript
  else {
    return null
  }
```
to `homekitAction()`, in case other buttonevent values might be generated in future.

**Comment by ebaauw** [comment]
That should do it, thanks.

**Comment by ebaauw** [comment]
Sorry, I thought I had merged this one already.  Must have slipped my mind.

**Comment by paolotremadio** [comment]
No worries :)

**Comment by SebSemmi** [comment]
added the sensor to the Phoscon App. In HomeKit it shows up as a button with the name  "lumi.vibration.aq1". DO I something wrong?

**Comment by ebaauw** [comment]
No.  It’s exposed as a ZHASwitch by deCONZ, which translates to a button in HomeKit.  The various notifications by the sensor for shake, drop, and tilt are mapped to different buttonevents, which are mapped to HomeKit’s _Single Press_, _Double Press_, and _Long Press_.

**Comment by CooperCGN** [comment]
Sorry that I have to come back to this old topic. I just set up my DeConz bridge and as a test added one of the above mentioned sensors. But I don't get the button in HomeKit. Is there anything I need to add to the config.json to have them exposed?

**Comment by ebaauw** [comment]
You need to set `”sensors”: true` in config.json (or whitelist the resource), see https://github.com/ebaauw/homebridge-hue#configuration.  Note that you need to restart homebridge after adding the device to deCONZ.  The new accessory appears in the HomeKit room where the homebridge accessory is in.

**Comment by CooperCGN** [comment]
Thank you, works now, I wasn't sure because the Wiki explicitly states hue bridge sensors, so I was thinking only of the original stuff like the hue motion sensor.

**Pull request merged**
