### PR TITLE
Add Paulmann 230V Dimmer

### PR DESCRIPTION
**Pull request by AntiHeld889**
Add Paulmann 230V Dimmer to knownLights.

### CODE REVIEW

**Comment by ebaauw** [comment]
What type does the dimmer report as?  Do you connect it to a Hue bridge or to a deCONZ gateway?  What does go wrong without this change?  I don't think the fix does anything?

**Comment by AntiHeld889** [comment]
How can i check what the dimmer reports? it's connected to a deCONZ gateway. Before the change it was shown as unknow device in the Homekit App and couldn*t turn on/off or dimm.

**Comment by ebaauw** [comment]
Can you please attach the debug dump file (see https://github.com/ebaauw/homebridge-hue#debug-dump-file)?

> Before the change it was shown as unknow device in the Homekit App and couldn*t turn on/off or dimm.

That's odd.  The Home app only shows a _Not Supported_ tile when the accessory has no services that it supports.  That means that homebridge-hue created an accessory, but no _Lightbulb_ service.  Maybe the dimmer also has an associated `/sensors` resource - the debug dump file will show that.

**Comment by AntiHeld889** [comment]
Okay, I mistook the device for another. It also works without the change.

Sorry

**Pull request closed without merging**
