### PR TITLE
Add support for controls to step brightness up and down.

### PR DESCRIPTION
**Pull request by jdberry**
Adds three controls: brightness step, brightness up, and brightness down. Each time brightness up or down are activated, they increase or decrease the brightness value by the step amount, respectively.

The brightness steppers are intended to be used with dimmer up/down pushbuttons, without requiring that the dimmers be paired directly to the lights.

This is somewhat experimental. I'm curious of your reaction and thoughts on this, @ebaauw. I'm also uncertain about a few points in the implementation, which we can hash out if you're positive on the idea.

The requires some matching changes to homebridge-lib.

### CODE REVIEW

**Comment by ebaauw** [comment]
> The brightness steppers are intended to be used with dimmer up/down pushbuttons, without requiring that the dimmers be paired directly to the lights.

I appreciate the functionality, but this is far better achieved using Hue bridge or deCONZ gateway rules, setting `state.bri_inc`.  HomeKit automations are less reliable and slower, providing not as good a user experience.  I only use HomeKit automations to control non-ZigBee devices (notably my Sonos zone players through homebridge-zp).

It does take some fiddling with the amount and transition time to get a smooth-ish dimming experience, see the default rules the Hue app creates for the Hue dimmer switch.  Still, the best user experience (smoothest dimming) by far is to let the dimmer control the lights directly.   Dimmers typically send _Move_ and _Stop_ ZigBee commands, which cannot be sent from the Hue / deCONZ API.

When using deCONZ, you don't need to pair the lights with the dimmer; just add them to the group that the dimmer sends its commands to (which is reported as `config.group` in the ZHASwitch resource).  This only works for dimmers that actually send commands (Trådfri, Hue), not for dimmers that only report button events (notably Xiaomi) and don't report `config.group`.

> The requires some matching changes to homebridge-lib.

I would prefer to implement the functionality using a single custom characteristic, which takes a value between -10 and 10 and defaults to 0.  See the _Volume Change_ characteristic for homebridge-zp.  Custom characteristics won't work with Apple's Home app, but this works perfectly with Eve.
https://github.com/ebaauw/homebridge-lib/blob/b2df202043ff5939cade4f46756e01ed9d056662/lib/MyHomeKitTypes.js#L317.

Also, better make the timeout interval to reset the characteristic configurable.  I'm using a default timeout of 500 msec for homebridge-zp.
https://github.com/ebaauw/homebridge-zp/blob/846602a02a54577e1460da008bd489155536c143/lib/ZpService.js#L133

I think it's better to send `state.bri_inc` instead of computing the new value for `state.bri`.  When the cached light state in the Hue bridge / deCONZ gateway is out of sync with the actual light state, the light will appear to be jumping brightness.  Note that setting `state.bri_inc` results in a ZigBee _Step_ command; setting `state.bri` results in a _Move to Level_.

**Comment by jdberry** [comment]
Thx for your thoughts, @ebaauw. I’ll try to absorb all of that and consider changes...

**Comment by jdberry** [comment]
I believe I've made the changes you suggested, @ebaauw. I'd be happy to have any further review. Thx.

**Comment by jdberry** [comment]
> I would prefer to implement the functionality using a single custom characteristic, which takes a value between -10 and 10 and defaults to 0. 

I set the increment range from -100 to 100 instead of -10 through 10. The 10% range seemed too small, and I couldn't convince myself there was any other obvious limit to the range accept 100%, but maybe you'll argue there should be something less. The broader range doesn't seem to limit utility at all, relative to a smaller range, as far as I can perceive, and could be useful for some purposes.

**Comment by ebaauw** [comment]
> I believe I've made the changes you suggested

Looks good to me, thanks.

> The broader range doesn't seem to limit utility at all, relative to a smaller range, as far as I can perceive, and could be useful for some purposes.

My only concern would be setting the characteristic manually from Eve or another HomeKit app.  It will be difficult to set a precise small value (1, 5, to 10) with a large range.  I don't think you'll ever want to use a relative brightness of 100% or -100%, since you could just as easily set the absolute brightness to 100% or 0%.  For setting the volume of my Sonos players, I find mapping short press to -1/+1 and long press to -10/+10 does fine.

> I'd be happy to have any further review. 

I still think this functionality is dangerous, in that it invites people to use HomeKit automations to control ZigBee lights from ZigBee switches (which is far better done in ZigBee or on the ZigBee hub/gateway), but it would be valid to control ZigBee lights from a non-ZigBee switch.  I'm half thinking about a config.json setting to expose this attribute, but I really want fewer settings instead of more.

I'll merge it for now.  We can always add changes later.

**Comment by jdberry** [comment]
Thanks, @ebaauw.

It feels like a 10% range is too small... but maybe 20% or 25% is a happy medium? That would give 4 or 5 increments, which is likely sufficient.

**Pull request merged**
