### PR TITLE
add 3A Smart Home DE support, fix dimming & type

### PR DESCRIPTION
**Pull request by xarbit**
Add support for known 3A Smart Home DE devices.

- fix false type and dimming

### CODE REVIEW

**Comment by ebaauw** [comment]
Do you connect these to a Hue bridge or to deCONZ?  In the latter case: this should be fixed in deCONZ.

**Comment by xarbit** [comment]
With deCONZ.. so I guess ill look in to how to fix this in deCONZ. Thanks

**Comment by xarbit** [comment]
can you give me a hint?

**Comment by ebaauw** [comment]
Suppress `state.bri` by whitelisting the device here:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/84cd1b0bdf4e66b5f244cf733c263166129fca62/light_node.cpp#L362-L373

With any luck that should retain the original _On/Off light_ device type.  deCONZ overrides it to _Dimmable light_ when `state.bri` is exposed:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/84cd1b0bdf4e66b5f244cf733c263166129fca62/light_node.cpp#L510-L514.

**Comment by xarbit** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2495

**Pull request closed without merging**
