### PR TITLE
Add support for TUYA Switches TS0042, TS0043, TS004F

### PR DESCRIPTION
**Pull request by nikbyte**

### CODE REVIEW

**Review by ebaauw — CHANGES_REQUESTED** [review]
Please keep the `case` blocks sorted by `manufacturername` value.

**Comment by nikbyte** [comment]
@ebaauw You mean sort these "_TZ3000_" blocks in different (a-z) order?
But how to be with this part?
```
        case '_TZ3000_i3rjdrwu':
        case '_TZ3000_dfgbtub0':
```

**Comment by ebaauw** [comment]
Yes, please.  For the combined block, sort them on the first entry, I’d say.  Not ideal, but better then duplicating the code.

I thought the deCONZ API would map these non-sensical Tuya names into something more easily consumed (like I did for the LIDL devices), but that didn’t materialise.

**Comment by nikbyte** [comment]
@ebaauw done

**Review by ebaauw — COMMENTED** [review]
Thanks

**Pull request merged**
